apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080   # Changed from 80 to 8080
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
          command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
